// UI localization table. See NOTICE.md.
using System;
using System.Collections.Generic;

namespace SpaceRangersHdSaveEditor
{
    internal static class EditorLocalization
    {
        private static readonly Dictionary<string, string> RussianByEnglish =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { " in the toolbar, select the game folder and language (the language determines which files get loaded)", " в тулбаре, выберите язык и папку с игрой (от языка зависит набор загружаемых файлов)" },
                { "— None —", "— Нет —" },
                { "— Planet or station —", "— Планета или станция —" },
                { "(derived)", "(производное)" },
                { "[current]", "[текущий]" },
                { "[item deleted]", "[предмет удалён]" },
                { "← Back", "← Назад" },
                { "← List", "← Список" },
                { "+ Add", "+ Добавить" },
                { "+ Add Extra Bonus", "+ Добавить экстра бонус" },
                { "+ Create", "+ Создать" },
                { "☐ Select", "☐ Выбрать" },
                { "250%", "250%" },
                { "300%", "300%" },
                { "350%", "350%" },
                { "400%", "400%" },
                { "450%", "450%" },
                { "500%", "500%" },
                { "AB Map Name", "Имя AB карты" },
                { "AB Weapon Type", "Тип в ЧД" },
                { "Abducted", "Похищен" },
                { "Absolute weapon", "Абсолютное оружие" },
                { "Abundance of Alcohol", "Избыток алкоголя" },
                { "Abundance of Food", "Избыток продовольствия" },
                { "Abundance of Luxury", "Избыток роскоши" },
                { "Abundance of Medicine", "Избыток медикаментов" },
                { "Abundance of Technology", "Избыток техники" },
                { "Abundance of Weapons", "Избыток оружия" },
                { "Accuracy", "Точность" },
                { "Ace", "Ас" },
                { "Achievement Stats", "Статистика достижений" },
                { "Achievements", "Достижения" },
                { "Acid", "Кислотный" },
                { "Acryn", "Акрин" },
                { "Acryn boost", "Акрин: усиление" },
                { "Acryn equipment availability", "Количество акриновых вещей в магазинах" },
                { "Acryn penalty", "Акрин: штраф" },
                { "Active", "Активно" },
                { "Additional", "Дополнительные" },
                { "Admiral", "Адмирал" },
                { "Agricultural planets ratio", "Относительное содержание в галактике аграрных планет" },
                { "Agriculture", "Аграрная" },
                { "AI purchases equipment from shops", "ИИ покупают оборудование в магазине" },
                { "AI ships fire missiles at max range", "ИИ корабли стреляют ракетами и торпедами с максимальной дистанции" },
                { "AI ships spawn with experience", "Пираты, мирные и военные корабли появляются с некоторым стартовым опытом" },
                { "AI value", "ИИ ценность" },
                { "Alcohol", "Алкоголь" },
                { "Alcohol Shortage", "Дефицит алкоголя" },
                { "all", "все" },
                { "Allow duplicate artefacts", "Использование нескольких однотипных артефактов" },
                { "Allow equipment swap in BH", "Смена оборудования в ЧД" },
                { "Ammo", "Зарядов" },
                { "Anarchy", "Анархия" },
                { "Angle", "Угол" },
                { "Anim Speed", "Скорость анимации" },
                { "Anim Step", "Шаг анимации" },
                { "Animation", "Анимация" },
                { "Antigravitazer", "Антигравитатор" },
                { "Applies to", "Применяется к" },
                { "Area damage", "Урон по площади" },
                { "Armor", "Броня" },
                { "Arms", "Оружие" },
                { "Array", "Массив" },
                { "Art Size", "Размер арт." },
                { "Art Sys Name", "Сис. имя арт." },
                { "Art. Tranclucator", "Транклюкатор (арт.)" },
                { "Art. Transmitter", "Трансфакторный маяк" },
                { "Artefact", "Артефакт" },
                { "Artefact (Custom)", "Мод.артефакт" },
                { "Artefact 2", "Артефакт 2" },
                { "Artefactor", "Артефактор" },
                { "Artefacts", "Артефакты" },
                { "Asteroid", "Астероид" },
                { "asteroid ", "астероид " },
                { "Asteroid density", "Количество астероидов" },
                { "Asteroid resist", "Защита от астероидов" },
                { "Asteroids", "Астероиды" },
                { "Asteroids destroyed", "Астероидов уничтожено" },
                { "At Ruins", "На станциях" },
                { "Ataman", "Атаман" },
                { "Atomic Vision", "Атомный визион" },
                { "Attack Count", "Кол. атак" },
                { "Attack type", "Тип" },
                { "Attacks", "Атаки" },
                { "Attract pirates", "Приманка для пиратов" },
                { "Auto", "Авто" },
                { "Auto Arrange", "Лучшее оборудование" },
                { "Auto-Battle", "Авто-бой" },
                { "Availability", "Доступность" },
                { "Avg Eq Value", "Ср.сила оборуд." },
                { "Avg Radius", "Средний радиус" },
                { "Avg Size", "Средний размер" },
                { "Avg Speed", "Ср. скорость" },
                { "Background (Idx)", "Фон (номер)" },
                { "Baron", "Барон" },
                { "Base Nod Cur", "Нод счет" },
                { "Base Speed", "Базовая скорость" },
                { "Battle", "Битва" },
                { "Battle Stats", "Боевая статистика" },
                { "Battles Won", "Выигранных ПБ" },
                { "BC construction", "Строительство БЦ" },
                { "Belongs to", "Принадлежит" },
                { "Bertor", "Бертор" },
                { "Bertors", "Берторы" },
                { "Best Star Ranger", "Лучший рейнджер" },
                { "BH enemies: battle royale mode", "Противники в ЧД враждуют между собой" },
                { "Bioworld", "Биомир" },
                { "Black Goo", "Черная жижа" },
                { "Black Hole", "Чёрная дыра" },
                { "Black holes", "Черные дыры" },
                { "Blast Wave Localizer", "Локализатор взрывной волны" },
                { "Blazer", "Блазер" },
                { "blazeroids", "блазероиды" },
                { "Block", "Имя раздела" },
                { "Blocker", "Клан.пират (броня)" },
                { "Bonus", "Бонус" },
                { "Bonus Info", "Информация о бонусе" },
                { "Bonuses", "Бонусы" },
                { "Boss", "Босс" },
                { "Bosses", "Боссы" },
                { "Bought", "Куплено" },
                { "Bridge", "Мостик" },
                { "Bridge BG", "Фон мостика" },
                { "Bridge Type", "Тип мостика" },
                { "broken", "сломан" },
                { "Browse…", "Обзор…" },
                { "Build stations near sector center", "Постройка станций близко к центру" },
                { "Buildings Destroyed", "Уничтожено строений" },
                { "Built-in save with a test database", "Встроенный сейв с тестовой базой данных" },
                { "Business Center", "Бизнес-центр" },
                { "Buy", "Покупка" },
                { "Buy Cost", "Стоимость покупки" },
                { "By Ship", "От корабля" },
                { "Cadet", "Кадет" },
                { "Camouflage", "Камуфляж" },
                { "Can Sell", "Можно продать" },
                { "Cancel", "Отмена" },
                { "Capacity", "Объем" },
                { "Caphasitor", "Кафаситор" },
                { "Capital", "Ср. капитал" },
                { "Cargo holds", "Трюмы" },
                { "Cargo Hook", "Захват" },
                { "Chain", "Цепной" },
                { "Chameleon Logic", "Мод.хамелеон" },
                { "Change [Pirate]", "Очков за ход [Пират]" },
                { "Change [Trader]", "Очков за ход [Торговец]" },
                { "Change [Warrior]", "Очков за ход [Военный]" },
                { "Charge", "Заряд" },
                { "Charm", "Обаяние" },
                { "Cheat detected", "Обнаружены читы" },
                { "Chg. Race", "Сменил расу" },
                { "Chg. Side", "Сменил сторону" },
                { "Cistern", "Цистерна" },
                { "Civilization", "Цивилизация" },
                { "Clan pirate", "Клан.пират" },
                { "Clan pirates", "Клановые пираты" },
                { "Clan Real", "Вступал в клан" },
                { "Close forms on outside click", "Закрывать формы при клике за пределами" },
                { "Close save to change language", "Закройте сейв для смены языка" },
                { "Coalition", "Коалиция" },
                { "Coalition (Active)", "Коалиция (Активные)" },
                { "Coalition (Military)", "Коалиция (Военные)" },
                { "Coalition (Passive)", "Коалиция (Пассивные)" },
                { "Coalition activity", "Активность коалиции" },
                { "Coalition Captured Dominator System", "Коалиция освободила систему от доминаторов" },
                { "Coalition Captured Pirate System", "Коалиция освободила систему от пиратов" },
                { "Coalition Defeated", "Поражение коалиции" },
                { "Coalition only", "Только у коалиции" },
                { "Coalition power", "Коалиция" },
                { "Coalition systems defended", "Защищено коал.систем" },
                { "Code", "Код" },
                { "Commander", "Командор" },
                { "Configure settings", "Настройте параметры" },
                { "Congratulations", "Поздравление" },
                { "Container", "Контейнер" },
                { "Contraband Pts", "Очки контрабанды" },
                { "Contract (days left)", "Контракт (ост.дней)" },
                { "Cost", "Стоимость" },
                { "Cost Mod.", "Мод.цены" },
                { "Costly Eq Ratio", "% Дорогого оборуд." },
                { "Count", "Количество" },
                { "Countable", "Контейнер" },
                { "Counteraction", "Противодействие" },
                { "Courageous", "Смелость" },
                { "CRC", "CRC" },
                { "CRC correction", "Коррекция CRC" },
                { "CRC Items", "CRC предметов" },
                { "CRC problems", "Проблемы CRC" },
                { "Create", "Создать" },
                { "Create object", "Создать объект" },
                { "Create RC", "Строительство ЦР" },
                { "Cur Planet", "Текущая планета" },
                { "Cur Standing", "Роль" },
                { "Cur Star", "Текущая система" },
                { "Cur Station", "Текущая станция" },
                { "Current Research", "Текущее исследование" },
                { "Current turn", "Текущий ход" },
                { "Custom", "Особый статус" },
                { "Custom Faction", "Мод.фракция" },
                { "Custom Info", "Мод.инфо" },
                { "Custom Infos", "Мод.инфо" },
                { "Custom Name", "Мод.имя" },
                { "Custom rules", "Тонкие настройки" },
                { "Custom Star Info", "Мод.инфо звезды" },
                { "Custom Star Infos", "Мод.инфо" },
                { "Custom Text", "Текст" },
                { "Custom Type", "Мод.тип" },
                { "Custom weapon", "Мод. оружие" },
                { "Custom Weapon deleted", "Мод.оружие удалено" },
                { "Custom weapon template", "Шаблон мод.оружия" },
                { "Custom Weapons", "Мод.оружие" },
                { "Customer Planet", "Планета заказчик" },
                { "CW Sys Name", "Сист. имя НО" },
                { "Damage", "Урон" },
                { "Damage buff (flagman)", "Баф урона (флагман)" },
                { "Damage Max", "Урон макс." },
                { "Damage Min", "Урон мин." },
                { "Damage Modifiers", "Модификаторы урона" },
                { "Damage Radius", "Радиус урона" },
                { "Damage set", "Шаблон урона" },
                { "Damage Type", "Тип урона" },
                { "Dark", "Тёмная" },
                { "Data", "Данные" },
                { "Data 0", "Данные 0" },
                { "Data 1", "Данные 1" },
                { "Data 2", "Данные 2" },
                { "Data 3", "Данные 3" },
                { "Database editor", "Редактор баз данных" },
                { "Date", "Дата" },
                { "Day", "День" },
                { "Day Before Occupy", "Дней до захвата" },
                { "Day w/o Create Ship", "Дней без создания корабля" },
                { "Day W/O Player", "Дней без игрока" },
                { "Days Landed", "Дней высадки" },
                { "Days w/ Player", "Дней с игроком" },
                { "DB warnings", "Предупреждения БД" },
                { "Debt", "Кредит" },
                { "Debt Amt", "Сумма кредита" },
                { "Debt Date", "Дата кредита" },
                { "Decelerating (Artefact Ex)", "Замедляющий (арт.)" },
                { "Decelerating (Artefact)", "Замедляющий (арт.)" },
                { "Decelerating (Weapon)", "Замедляющий (оружие)" },
                { "Def Generator", "Генератор защиты" },
                { "Def Power %", "Мощность" },
                { "Defeated (turn ", "Побеждён (ход " },
                { "Defend", "Защита" },
                { "Defend ship", "Защита корабля" },
                { "Defend system", "Защита системы" },
                { "Defense", "Защита" },
                { "Deficit", "Дефицит" },
                { "Deflected Shots", "Рикошетов от игрока" },
                { "Delete", "Удалить" },
                { "Delivery", "Доставка" },
                { "Dematerializer", "Дематериализатор" },
                { "Democracy", "Демократия" },
                { "Dep. Date", "Дата депозита" },
                { "Deposit", "Депозит" },
                { "Deposit %", "% Депозита" },
                { "Deposit Day", "День депозита" },
                { "Des X", "Цель X" },
                { "Des Y", "Цель Y" },
                { "Description", "Описание" },
                { "Desire Confl.", "Агрессия" },
                { "Destroy", "Уничтожение" },
                { "Destroy ship", "Уничтожение корабля" },
                { "destroyed", "уничтожена" },
                { "Destructive", "Деструктивный" },
                { "Detect", "Обнаружение" },
                { "Dictatorship", "Диктатура" },
                { "Difficulty", "Сложность" },
                { "Diplomat", "Дипломат" },
                { "Diplomats", "Дипломаты" },
                { "Direction", "Направление" },
                { "Disable Ship Production", "Запрет производства кораблей" },
                { "Disabled", "Отключено" },
                { "Disintegrator", "Дезинтегратор" },
                { "Distance", "Расстояние" },
                { "Distress signal", "Аварийный сигнал" },
                { "Docking", "Сворачивание" },
                { "Dom. aggression", "Агрессивность доминаторов" },
                { "Dom. equipment level", "Оснащение доминаторов" },
                { "Dom. Series", "Дом.серия" },
                { "Dom. spawn rate", "Темп воспроизводства доминаторов" },
                { "Dom. Type", "Тип доминатора" },
                { "Dominator", "Доминатор" },
                { "Dominator (Fanaticism)", "Доминатор от фанатизма" },
                { "Dominator Series", "Серии доминаторов" },
                { "Dominators", "Доминаторы" },
                { "Dominators (by type)", "Убийств доминаторов" },
                { "Dominators Attack", "Нападение доминаторов" },
                { "Dominators Captured Coalition System", "Доминаторы захватили систему коалиции" },
                { "Dominators Captured Pirate System", "Доминаторы захватили пиратскую систему" },
                { "Dominators Defeated", "Поражение доминаторов" },
                { "Dominators power", "Доминаторы" },
                { "Dominion", "Доминион" },
                { "Drain", "Поглощающий" },
                { "Droid", "Дроид" },
                { "Droid block", "Блок дроида" },
                { "Drop *.sav file here", "Перетащите *.sav файл сюда" },
                { "Drop a *.sav file into the area on the right or click the ", "Перетащите *.sav файл в область справа или нажмите кнопку " },
                { "Drop Item Entry", "Выпадающий предмет" },
                { "Drop Items", "Выпадающие предметы" },
                { "Dump", "Дамп" },
                { "Durability", "Прочность" },
                { "Duration", "Длительность" },
                { "DWord", "Беззнаковое" },
                { "Earned", "Полученные" },
                { "Easy (50%)", "Легко (50%)" },
                { "Economy", "Экономика" },
                { "Economy & Drop", "Экономика и дроп" },
                { "Edit", "Редактирование" },
                { "Edit Asteroid", "Редактирование астероида" },
                { "Edit Black Hole", "Редактирование чёрной дыры" },
                { "Edit Bridge Ship →", "Редактировать мостик →" },
                { "Edit Custom Weapon", "Редактирование мод.оружия" },
                { "Edit Drop Item", "Редактирование выпадающего предмета" },
                { "Edit Galactic Gate", "Редактирование гал.перехода" },
                { "Edit Galaxy", "Редактирование галактики" },
                { "Edit Garbage", "Редактирование мусора" },
                { "Edit Interface", "Редактирование интерфейса" },
                { "Edit Item", "Редактирование предмета" },
                { "Edit Journal Record", "Редактирование журнала" },
                { "Edit Message", "Редактирование сообщения" },
                { "Edit Missile", "Редактирование ракеты" },
                { "Edit Old Quest", "Редактирование старого квеста" },
                { "Edit Planet", "Редактирование планеты" },
                { "Edit Planet News", "Редактирование новости" },
                { "Edit Quest", "Редактирование квеста" },
                { "Edit Robot Map", "Редактирование статистики ПБ карты" },
                { "Edit Script", "Редактирование скрипта" },
                { "Edit Script Cache", "Редактирование кэша скрипта" },
                { "Edit Script Item", "Редактирование скрипт.предмета" },
                { "Edit Script Ship", "Редактирование скрипт.корабля" },
                { "Edit Ship", "Редактирование корабля" },
                { "Edit Ship Mod Info", "Редактирование мод.инфо корабля" },
                { "Edit star", "Редактировать звезду" },
                { "Edit Star Mod Info", "Редактирование мод.инфо звезды" },
                { "Edit Station", "Редактирование станции" },
                { "Edit Storage Item", "Редактирование предмета на складе" },
                { "Edit Stored Item", "Редактирование предмета хранилища" },
                { "Edit Variable", "Редактирование переменной" },
                { "Edit War Operation", "Редактирование воен.операции" },
                { "Electron Cutter", "Электронный резак" },
                { "Eminent [Pirate]", "Очки выдающ. [Пират]" },
                { "Eminent [Trader]", "Очки выдающ. [Торговец]" },
                { "Eminent [Warrior]", "Очки выдающ. [Военный]" },
                { "Eminent Pirate", "Выдающийся пират" },
                { "Eminent Trader", "Выдающийся торговец" },
                { "Eminent Warrior", "Выдающийся воин" },
                { "Employer", "Наниматель (контракт)" },
                { "Empty", "Пусто" },
                { "Empty array", "Пустой массив" },
                { "Enable classic hyperspace encounters", "Сражения с гиперпиратами при перелетах между системами" },
                { "Enable node trade on pirate bases", "Продажа нодов на пиратских станциях" },
                { "Enabled", "Включено" },
                { "End Turn", "Ход конца" },
                { "Enemy damage in BH", "Урон противников в ЧД" },
                { "Enemy hp in BH", "Выносливость противников в ЧД" },
                { "Enemy loot quality in BH", "Качество оборудования, выпадающего из противников в ЧД" },
                { "Enemy Spd", "Ср.скорость врагов" },
                { "Energotron", "Энерготрон" },
                { "Energy", "Энергетический" },
                { "Engine", "Двигатель" },
                { "entering the black hole", "вход в черную дыру" },
                { "Environment", "Окружение" },
                { "Equantor", "Эквентор" },
                { "Equipment", "Оборудование" },
                { "Equipment Sets", "Сеты оборудования" },
                { "Equipments", "Оборудование" },
                { "Erimeter", "Эриметр" },
                { "Errors", "Ошибки" },
                { "Esodapher", "Эсодафер" },
                { "Ethers", "Ethers" },
                { "Events", "События" },
                { "Excl. Rating", "Исключен из рейтинга" },
                { "Exp points earned", "Очки опыта за убийства" },
                { "Expert (200%)", "Невозможно (200%)" },
                { "Exploder", "Взрывной" },
                { "Exploitable", "Используется" },
                { "Explored", "Исследовано" },
                { "Explosion Graph", "Графика взрыва" },
                { "Extra", "Экстра" },
                { "Extra rangers count", "Количество дополнительных рейнджеров" },
                { "Face", "Портрет" },
                { "Faction", "Фракция" },
                { "Fei", "Фэяне" },
                { "Fei only", "Только фэяне" },
                { "File", "Файл" },
                { "Filter by name…", "Поиск по имени…" },
                { "Finance", "Финансы" },
                { "Fiver", "Пятерик" },
                { "Flagman", "Флагман" },
                { "Flagmans", "Флагманы" },
                { "Flags", "Флаги" },
                { "Flagship", "Флагман" },
                { "Flanker", "Клан.пират (урон)" },
                { "Float", "Дробное" },
                { "Flow Blaster", "Потоковый бластер" },
                { "Flux", "Лезка" },
                { "Fly Date", "Ход прыжка" },
                { "Fly To Star", "Прыжок в систему" },
                { "Follow", "Преследование" },
                { "follow ship ", "преследование корабля " },
                { "Follow Type", "Тип следования" },
                { "Food", "Продукты" },
                { "Food Shortage", "Дефицит продовольствия" },
                { "Form Name", "Имя формы" },
                { "Forsage", "Форсаж" },
                { "Fragility", "Хрупкость" },
                { "Fragmentation Cannon", "Осколочное орудие" },
                { "Frame", "Кадр" },
                { "free", "свободный" },
                { "free (at base)", "свободный (на базе)" },
                { "free (on planet)", "свободный (на планете)" },
                { "Free Space", "Ср.свободный объем" },
                { "From Angle", "Угол выстрела" },
                { "From Angle (old)", "Угол выстрела (стар.)" },
                { "From Ship", "От корабля" },
                { "Frostix", "Отморозки" },
                { "Fuel", "Топливо" },
                { "Fuel scoped from suns", "Заправлено от звезд" },
                { "Fuel tank", "Топливный бак" },
                { "Fuel Tanks", "Топливный бак" },
                { "Gaal", "Гаальцы" },
                { "Gaals only", "Только гаальцы" },
                { "Galaxy", "Галактика" },
                { "Galaxy (stored items)", "Галактика (хранилище)" },
                { "Galaxy Event", "Галактическое событие" },
                { "Galaxy map", "Карта галактики" },
                { "Galaxy News", "Галактические новости" },
                { "Galaxy structure", "Структура галактики" },
                { "Game DB", "БД игры" },
                { "Game folder", "Папка с игрой" },
                { "Game wiki", "Энциклопедия по игре" },
                { "Garbage", "Мусор" },
                { "Gate", "Гал.переход" },
                { "Gates", "Гал.переходы" },
                { "Gatrix matrix", "Гатрикс матрица" },
                { "General", "Общие" },
                { "Global Vars", "Глобальные переменные" },
                { "Gone Items", "Закопанные предметы" },
                { "Good Ships", "Мирных кораблей" },
                { "Goods", "Товары" },
                { "GoToGov", "В правительство" },
                { "Government", "Строй" },
                { "Graph", "Графика" },
                { "Graph Name", "Графика" },
                { "Graph Star", "Графика звезды" },
                { "Graph Trans", "Прозрачность" },
                { "Graphics", "Графика" },
                { "Graphics Radius", "Радиус графики" },
                { "Group", "Группа" },
                { "Group at date", "Группа по дате" },
                { "Group in place", "Группа на месте" },
                { "Group Order", "Приказ операции" },
                { "GTL", "ГТУ" },
                { "Hangar", "Ангар" },
                { "Hard (150%)", "Тяжело (150%)" },
                { "Health drained", "Здоровье" },
                { "Height", "Высота" },
                { "Hidden (click to reveal)", "Закрыт (нажмите, чтобы открыть)" },
                { "Hide", "Закрыть" },
                { "Hide docked ships", "Скрывать корабли на станциях / планетах" },
                { "Hide Tags", "Теги" },
                { "High Pirate Activity", "Множество пиратов" },
                { "Hill", "Горы" },
                { "Hit", "Урон" },
                { "Hit After", "Урон после програм." },
                { "Hit Chance", "Шанс попадания" },
                { "Hit Player", "Урон от игрока" },
                { "Hit Points", "Очки жизни" },
                { "Hold", "Трюм" },
                { "Hold Filter", "Фильтр трюма" },
                { "Home Planet", "Родная планета" },
                { "Hook", "Захват" },
                { "Hook max spd", "Макс.скор.захвата" },
                { "Hook min spd", "Мин.скор.захвата" },
                { "Hook Radius", "Радиус захвата" },
                { "Hull", "Структура" },
                { "Hull size scaling", "Размер корпусов в магазине" },
                { "Hull Type", "Тип корпуса" },
                { "Hypergenerator", "Гипергенератор" },
                { "Hyperspace Jump Planned", "ВБ планирует гиперпрыжок" },
                { "Icon", "Иконка" },
                { "ID", "ID" },
                { "Identifier", "Идентификатор" },
                { "Idx", "Номер" },
                { "If the removed mod contains micromodules or Akrin hulls, re-save and reopen in the editor to correct the removed bonuses and graphics.", "Если удаляемый мод содержит микромодули и акрины, необходимо пересохранить сейв и повторно открыть редактором для коррекции удаляемых бонусов и графики." },
                { "iKeller", "iКеллер" },
                { "Illness Count", "Болел" },
                { "Image", "Изображение" },
                { "IMHO-9000", "ИМХО-9000" },
                { "Immunity", "Иммунитет" },
                { "Imp. Shields", "Щиты" },
                { "In all systems", "Во всех системах" },
                { "In Hold", "В трюме" },
                { "In Hyper Space", "В гипере" },
                { "In Prison", "Был в тюрьме" },
                { "In Use", "Используется" },
                { "Increases with the player hull size", "Растет с увеличением корпуса игрока" },
                { "Industrial", "Индустриальная" },
                { "Industrial Laser", "Промышленный лазер" },
                { "Industrial planets ratio", "Относительное содержание в галактике индустриальных планет" },
                { "Infections", "Болезни" },
                { "Infections & Stimulators", "Болезни и стимуляторы" },
                { "Infections & Stimulators Log", "Болезни и стимуляторы" },
                { "Info", "Инфо" },
                { "Info 1", "Планета инфо [1]" },
                { "Info 2", "Планета инфо [2]" },
                { "Info Text", "Текст информации" },
                { "Information", "Информация" },
                { "Init", "Init" },
                { "Init Vars", "Init переменные" },
                { "Int", "Целое" },
                { "Int. Duration", "Длительность" },
                { "Int. Strategy", "Стратегия" },
                { "Int. Target", "Цель" },
                { "Interceptor", "Перехватчик" },
                { "Interceptors", "Перехватчики" },
                { "Intercom", "Интерком" },
                { "Intercom 2", "Прочитанный интерком" },
                { "Interface", "Интерфейс" },
                { "Investment", "Инвестиции" },
                { "Investment Days", "Инвестиции" },
                { "Iron will", "Железная воля" },
                { "Iron Zoopie", "Железные жупи" },
                { "Item", "Предмет" },
                { "item ", "предмет " },
                { "Item already used in another script", "Предмет уже есть в другом скрипте" },
                { "Item ID", "ID предмета" },
                { "Item type", "Тип предмета" },
                { "Items", "Предметов" },
                { "Items in shops", "Предметы в магазинах" },
                { "Items in space", "Предметы в космосе" },
                { "Items on planets", "Предметы на планетах" },
                { "Items using this template were removed:", "Предметов с этим шаблоном удалено:" },
                { "Journal", "Журнал" },
                { "Journal Entry", "Запись в журнале" },
                { "Jump", "Прыжок" },
                { "Jump hole", "Вход в ЧД" },
                { "jump to system ", "прыжок в систему " },
                { "Junior Droid", "Дроид младший" },
                { "Junk limit before AI cleanup", "Количество предметов в системе, после которого пилоты начинают их расстреливать" },
                { "k Cost", "Мод.цены" },
                { "Kamikaze", "Камикадзе" },
                { "Keller", "Келлер" },
                { "Keller Attack", "Атака Келлера" },
                { "kelleroids", "келлероиды" },
                { "Khan", "Хан" },
                { "Kid", "Юнга" },
                { "Kill Cur Custom", "Мод.кораблей" },
                { "Kill Cur Sys", "Убийств в системе" },
                { "Kill Dom.", "Доминаторов" },
                { "Kill Pacific", "Мирных" },
                { "Kill Pirates", "Пиратов" },
                { "Kill Rangers", "Рейнджеров" },
                { "Kill Ships", "Кораблей" },
                { "Kill Warriors", "Военных" },
                { "Killed in Black Hole", "Убито в ЧД" },
                { "Killed in Hyperspace", "Убито в гипере" },
                { "Kills", "Убийства" },
                { "Kills & Builds", "Потери и постройки" },
                { "Klig", "Клиг" },
                { "Land", "Суша" },
                { "Land Storage", "Выгрузка трюма" },
                { "Land Type", "Тип поверхности" },
                { "landing", "посадка" },
                { "landing on planet ", "посадка на планету " },
                { "landing on ship ", "посадка на корабль " },
                { "landing on station ", "посадка на станцию " },
                { "Language", "Язык" },
                { "Last", "Последний" },
                { "Last Date", "Ход последней ПБ" },
                { "Last Distance Min", "Мин. посл. расстояние" },
                { "Last Dom. Date", "Дата владения [доминаторы]" },
                { "Last fuel tank", "Последний бак" },
                { "Last Next Day", "Ход запуска логики" },
                { "Last Owners", "Последний владелец" },
                { "Last Pirate Date", "Дата владения [пираты]" },
                { "Last Planet", "Последняя планета" },
                { "Last Pos X", "Последняя поз. X" },
                { "Last Pos Y", "Последняя поз. Y" },
                { "Last Run (turn number)", "Последний запуск (номер хода)" },
                { "Last Station", "Последняя станция" },
                { "Leader", "Истребитель" },
                { "Leadership", "Лидерство" },
                { "Legacy & AI", "Старые механики и ИИ" },
                { "Legacy unique hulls (bolide, killer, rock)", "Старые уникальные корпуса (Болид, Убийца, Скала)" },
                { "Legal", "Легальность" },
                { "Lib. Kills", "При освобождении" },
                { "Liberated Sys", "Освободил систем" },
                { "Liberation Date", "Дата освобождения" },
                { "Light", "Светлая" },
                { "Limited by technical level", "Ограничен техническим уровнем" },
                { "Liner", "Лайнер" },
                { "Liners", "Лайнеры" },
                { "Lirecron", "Лирекрон" },
                { "Live", "Жив" },
                { "Loads", "Загрузок" },
                { "Location", "Местоположение" },
                { "Log", "Лог" },
                { "Lost subsidy", "Помощь малоимущим" },
                { "Lost Target", "Потерянная цель" },
                { "Lost Type", "Тип потерянной цели" },
                { "Luck", "Удача" },
                { "Luxury", "Роскошь" },
                { "Luxury Shortage", "Дефицит роскоши" },
                { "M", "млн." },
                { "Magnetic", "Магнитный" },
                { "Maloc", "Малоки" },
                { "Malocs only", "Только малоки" },
                { "Manual Attack", "Ручная атака" },
                { "Map", "Карта" },
                { "Map Label", "Мод.метка" },
                { "Mass", "Масса" },
                { "Material", "Материал" },
                { "Matter Psi-Accelerator", "Пси-ускоритель материи" },
                { "Max", "Макс." },
                { "Max Ammo", "Макс. зарядов" },
                { "Max Dmg", "Макс. урон" },
                { "Max Energy", "Максимум энергии" },
                { "Max loot value", "Максимальная стоимость выпадающих предметов" },
                { "Max.distance", "Макс.дистанция" },
                { "MC construction", "Строительство МЦ" },
                { "Med Policy", "Мед.страховка" },
                { "Medical Center", "Медицинский центр" },
                { "Medicine", "Медикаменты" },
                { "Menoc", "Менок" },
                { "Message Text", "Сообщение" },
                { "Messages", "Сообщения" },
                { "Micro Module", "Микромодуль" },
                { "MicroModule", "Микромодуль" },
                { "Micromodules", "Микромодули" },
                { "Military Base", "Военная база" },
                { "Min", "Мин." },
                { "Min Dmg", "Мин. урон" },
                { "Min.distance", "Мин.дистанция" },
                { "Mineral Deposit", "Богатые залежи минералов" },
                { "Mineral Shortage", "Дефицит минералов" },
                { "Minerals", "Минералов" },
                { "Mining Factor", "Коэф.минералов" },
                { "Misc", "Разное" },
                { "Miss", "Пропавший" },
                { "Miss. MaxSpeed", "Макс. скорость ракеты" },
                { "Miss. MinSpeed", "Мин. скорость ракеты" },
                { "Miss. Radius", "Радиус ракеты" },
                { "Missile", "Ракета" },
                { "missile ", "ракета " },
                { "Missile Launcher", "Ракетомет" },
                { "Missile No.", "Номер ракеты" },
                { "Missile spd", "Скор.ракеты" },
                { "Missiles", "Ракеты" },
                { "Missiles using this template were removed:", "Ракет с этим шаблоном удалено:" },
                { "Mixed", "Смешанная" },
                { "Mixed economy planets ratio", "Относительное содержание в галактике планет со смешанной экономикой" },
                { "Mobility", "Маневренность" },
                { "Mod Base", "Мод.база" },
                { "Mod info", "Мод.инфо" },
                { "Mod loot", "Мод.трофеи" },
                { "Mod missile with splash", "Мод.ракета со сплешем" },
                { "Mod storage", "Мод.хранилище" },
                { "Mod weapon", "Мод.оружия" },
                { "ModCFG", "ModCFG" },
                { "Mode: Correction", "Режим: Коррекция" },
                { "Mode: Read as is", "Режим: Как есть" },
                { "Moderate Pirate Activity", "Есть пираты" },
                { "Mods", "Моды" },
                { "Mods list", "Список модов" },
                { "Monarchy", "Монархия" },
                { "Money", "Деньги" },
                { "Money / Capital", "Деньги / Капитал" },
                { "Moral", "Характер" },
                { "Mountains", "Горы" },
                { "Move", "Перемещение" },
                { "moving", "передвижение" },
                { "Multiresonator", "Мультирезонатор" },
                { "My projects for SR", "Мои проекты для SR" },
                { "Name", "Название" },
                { "Name or type… (Enter)", "Имя или тип… (Enter)" },
                { "Name…", "Название…" },
                { "Nanitoids", "Нанитоиды" },
                { "Narcotics", "Наркотики" },
                { "Natural [non-container]", "Натуральный [не контейнер]" },
                { "Near", "Держаться около" },
                { "Nearest group", "Ближайшая группа" },
                { "Neutral", "Нейтралы" },
                { "New", "Новые очки пирата" },
                { "New Black Hole Discovered", "Обнаружена черная дыра" },
                { "New Position", "Новая позиция" },
                { "New Size", "Новый размер" },
                { "New Space Station", "Построена новая станция" },
                { "News", "Новости" },
                { "No Come Dominator", "Запрет дом.атаки" },
                { "No corrections", "Нет исправлений" },
                { "No CRC errors", "Нет ошибок CRC" },
                { "No Delta", "Урон без разброса" },
                { "No deployed satellites", "Нет развёрнутых зондов" },
                { "No deployed ship", "Нет развернутого корабля" },
                { "No Drop", "Запрет выпадения предметов" },
                { "No errors", "Нет ошибок" },
                { "No galaxy events", "Нет галактических событий" },
                { "No Jump", "Прыжок запрещен" },
                { "No Landing", "Запрет посадки" },
                { "No matches", "Нет совпадений" },
                { "No messages", "Нет сообщений" },
                { "No mods", "Нет модов" },
                { "No Pirate Activity", "Нет пиратов" },
                { "No results", "Нет результатов" },
                { "No Rnd Events", "Запрет случайных событий" },
                { "No robbing", "Запрет грабежа" },
                { "No robbing by pirates", "Пираты не грабят" },
                { "No robbing by rangers", "Рейнджеры не грабят" },
                { "No Scan", "Запрет сканирования" },
                { "No Shop Upd", "Запрет обновления магазина" },
                { "No Sound", "Без звука" },
                { "No star selected", "Звезда не выбрана" },
                { "No storage items", "Нет предметов на складе" },
                { "No Talk", "Запрет разговоров" },
                { "No Target", "Запрет атаки" },
                { "No tech knowledge requirements", "Использование и ремонт оборудования без ограничений" },
                { "Node drop rate", "Дроп нодов из доминаторов" },
                { "Nods", "Ноды" },
                { "Non-Lethal", "Нелетальный" },
                { "Non-linear speed calculation", "Нелинейная формула скорости корабля" },
                { "None", "Ничего" },
                { "Noobie", "Салага" },
                { "Normal", "Обычный" },
                { "Normal (100%)", "Нормально (100%)" },
                { "Normal end", "Обычное завершение" },
                { "Normal off-screen station combat", "Вдали от игрока станции сражаются как обычно" },
                { "Not Active", "Не активно" },
                { "Not for sale", "Не продается" },
                { "Not for sale (repair with nods)", "Не продается (ремонт за ноды)" },
                { "not found", "не найден" },
                { "Not loaded", "Не загружена" },
                { "Nozzlenator", "Сопланатор" },
                { "NPC Stats", "Статистика NPC" },
                { "Number", "Номер" },
                { "Object", "Объект" },
                { "Object Name", "Имя объекта" },
                { "Object type", "Тип объекта" },
                { "Objects", "Объекты" },
                { "Oblivion Connector", "Обливионный коннектор" },
                { "of", "из" },
                { "Off", "Выкл" },
                { "Old", "Старое" },
                { "Old Position", "Старая позиция" },
                { "Old Quest", "Старое задание" },
                { "Old Quests", "Пройденные задания" },
                { "Old Size", "Старый размер" },
                { "On", "Вкл" },
                { "On Act Code", "On Act Code" },
                { "On Planets", "На планетах" },
                { "On sale", "Распродажа" },
                { "On Use Code", "On Use Code" },
                { "Open", "Открыть" },
                { "Open ", "Откройте " },
                { "Open a save file", "Откройте сейв-файл" },
                { "Open demo save", "Открыть демо-сохранение" },
                { "or", "или" },
                { "or try without installing the game", "или попробуйте без установки игры" },
                { "Orbit", "Орбита" },
                { "Orbit Cnt", "Кол. орбит" },
                { "Orbit Radius", "Радиус орбиты" },
                { "Order", "Приказ" },
                { "Order End", "Конец приказа" },
                { "Order Object", "Объект приказа" },
                { "Order Type", "Тип приказа" },
                { "Orders", "Приказы" },
                { "Origin", "Источник" },
                { "Owner", "Фракция" },
                { "Owner Ship", "Корабль владельца" },
                { "Owners", "Владелец" },
                { "Palette", "Палитра" },
                { "Parameters", "Параметры" },
                { "PB construction", "Строительство ПБ" },
                { "Peleng", "Пеленги" },
                { "Pelengs only", "Только пеленги" },
                { "People", "Люди" },
                { "People only", "Только люди" },
                { "Percent", "Процент" },
                { "Percentage [1]", "Процент [1]" },
                { "Percentage [2]", "Процент [2]" },
                { "Phi X / Y", "Phi X / Y" },
                { "Pick Up Size", "Размер захвата" },
                { "Pilot", "Пилот" },
                { "Pilot Race", "Раса пилота" },
                { "Pirate", "Пират" },
                { "Pirate aggression", "Агрессивность пиратов" },
                { "Pirate Attack", "Атака пиратов" },
                { "Pirate Base", "Пиратская база" },
                { "Pirate Built", "Производства пиратов" },
                { "Pirate clan", "Пиратский клан" },
                { "Pirate Clan (Military)", "Пиратский клан (Военные)" },
                { "Pirate Clans", "Пиратов клана" },
                { "Pirate Lic.", "Пиратская лицензия" },
                { "Pirate Pts", "Очки пирата" },
                { "Pirate Rank", "Пиратский ранг" },
                { "Pirate Rank Points", "Очки пиратского ранга" },
                { "Pirate Type", "Тип пирата" },
                { "Pirates", "Пираты" },
                { "Pirates (Active)", "Пираты (Активные)" },
                { "Pirates (Passive)", "Пираты (Пассивные)" },
                { "Pirates Captured Coalition System", "Пираты захватили систему Коалиции" },
                { "Pirates Captured Dominator System", "Пираты захватили систему доминаторов" },
                { "Pirates Defeated", "Поражение пиратов" },
                { "Pirates freed", "Пираты" },
                { "Pirates only", "Только у пиратов" },
                { "Pirates power", "Пираты" },
                { "Pirates subsidy", "Субсидия пиратам" },
                { "Place", "Место" },
                { "Plain", "Обычный" },
                { "Planet", "Планета" },
                { "Planet (customer)", "Планета (заказчик)" },
                { "Planet News", "Новость планеты" },
                { "Planet: ", "Планета: " },
                { "Planetary battles", "Планетарные бои" },
                { "Planets", "Планет" },
                { "Planets visited", "Планет посещено" },
                { "Player", "Игрок" },
                { "Player bridge", "Мостик игрока" },
                { "Player money", "Деньги игрока" },
                { "Player name", "Имя игрока" },
                { "Player on Bridge", "Игрок на мостике" },
                { "Player probes", "Зонды игрока" },
                { "Player race", "Раса игрока" },
                { "Player Ship (id: ", "Корабль игрока (id: " },
                { "Player storage", "Склад игрока" },
                { "Plr Racket Turn", "Ход рэкета игроком" },
                { "Points", "Очки" },
                { "Polar Angle", "Полярный угол" },
                { "Polarizer", "Поляризатор" },
                { "Population", "Население" },
                { "Pos", "Позиция" },
                { "Pos X", "Позиция X" },
                { "Pos Y", "Позиция Y" },
                { "Position", "Позиция" },
                { "Position / Motion", "Позиция / Движение" },
                { "Position & Geometry", "Позиция и геометрия" },
                { "Power", "Мощность" },
                { "Power %", "Мощность" },
                { "Press Enter or Search to find objects", "Нажмите Enter или Найти для поиска" },
                { "Prev Star", "Предыдущая система" },
                { "Preview", "Превью" },
                { "Price", "Цена" },
                { "Priority", "Приоритетный" },
                { "Prison", "Тюрьма" },
                { "Probability", "Вероятность" },
                { "Probability Analyzer", "Вероятностный анализатор" },
                { "Prog. Date", "Ход начала прогр." },
                { "Prog. Name", "Программа" },
                { "Program Researched", "Исследование завершено" },
                { "Programmes", "Программы" },
                { "Programs used", "Программ использовано" },
                { "Progress (0-100)", "Прогресс (0-100)" },
                { "Projectile", "Снаряд" },
                { "Prolonger", "Пролонгер" },
                { "Properties", "Свойства" },
                { "Proportionar", "Пропорционар" },
                { "Proprietor", "Владелец" },
                { "Proton", "Протон" },
                { "Protoplasm", "Протоплазма" },
                { "Quark bomb", "Кварковая бомба" },
                { "Quest", "Задание" },
                { "Quest #", "Номер квеста" },
                { "Quest completed", "Квест выполнен" },
                { "Quest failed", "Квест провален" },
                { "Quest received", "Получен квест" },
                { "Quests", "Задания" },
                { "Race", "Раса" },
                { "Races", "Расы" },
                { "Radar", "Радар" },
                { "Radius", "Радиус" },
                { "Radius Stop", "Радиус остановки" },
                { "Raider", "Рейдер" },
                { "Rals", "Ралс" },
                { "Ranger", "Рейнджер" },
                { "Ranger Center", "Центр рейнджеров" },
                { "Ranger Imprisoned", "Рейнджер в тюрьме" },
                { "Rangers", "Рейнджеров" },
                { "Rangers & Inventions", "Рейнджеры и изобретения" },
                { "Rangers subsidy", "Субсидия рейнджерам" },
                { "Rank", "Коалиционный ранг" },
                { "Rank & Statistics", "Звание и Статистика" },
                { "Rank Points", "Очки ранга коалиции" },
                { "Re-roll rng on save load", "Результат случайных событий меняется при загрузке сохранения" },
                { "Read", "Прочитано" },
                { "Ready", "Загружена" },
                { "Recently Dropped", "Выброшенные предметы" },
                { "Recover HP", "Мощность" },
                { "Ref (int)", "Ссылка (int)" },
                { "Referenced Objects", "Связанные объекты" },
                { "Reg", "Регион" },
                { "Rejection", "Отклонено" },
                { "Related Objects", "Связанные объекты" },
                { "Relations to Rangers", "Отношение к рейнджерам" },
                { "Repair", "Поломки" },
                { "Repair debuff (flagman)", "Дебаф ремонта (флагман)" },
                { "Repair Droid", "Дроид" },
                { "Repair Robot", "Дроид" },
                { "Repairs", "Чинит" },
                { "Republic", "Республика" },
                { "Research", "Исследования" },
                { "Research (Bosses)", "Исследования" },
                { "Research Station", "Научная база" },
                { "Resource editor", "Редактор ресурсов" },
                { "Restrict dominator racial weapons", "Особое вооружение, разработанное другими сериями, рядовым доминаторам не доступно" },
                { "Restricted to AI", "Запрет для ИИ" },
                { "Restricted to all", "Запрет для всех" },
                { "Results", "Результатов" },
                { "Revolt: Anarchy", "Революция: Анархия" },
                { "Revolt: Democracy", "Революция: Демократия" },
                { "Revolt: Dictatorship", "Революция: Диктатура" },
                { "Revolt: Monarchy", "Революция: Монархия" },
                { "Revolt: Republic", "Революция: Республика" },
                { "Reward", "Награда" },
                { "Reward Planet", "Планета награждения" },
                { "Reward Views", "Видимых медалей" },
                { "Rewards", "Медали" },
                { "Rings", "Кольца" },
                { "Rnd", "Пост. зерно" },
                { "Rnd Out", "Изм. зерно" },
                { "Robbed By Plr", "Ограблен игроком" },
                { "Robot Map", "Планетарные бои" },
                { "Robots Built", "Построено роботов" },
                { "Robots Destroyed", "Уничтожено роботов" },
                { "Rocket", "Ракета" },
                { "Rocketang", "Ракетанг" },
                { "Rogeria", "Роджерия" },
                { "Rookie", "Новичок" },
                { "Rough", "Головорез" },
                { "Ruins", "Станция" },
                { "Ruins & Specials", "Станции и спецкорабли" },
                { "Running", "Активный" },
                { "Safe Radius", "Безопасный радиус" },
                { "Safety", "Безопасность" },
                { "Sale", "Продажа" },
                { "Sat. Type", "Тех.уровень" },
                { "Satellite", "Зонд" },
                { "Satellites", "Зонды" },
                { "Satellites on Planets", "Зонды на планетах" },
                { "Save", "Сохранить" },
                { "Save editor for Space Rangers HD", "Редактор сохранений для Space Rangers HD" },
                { "Save file editor", "Редактор сейв-файлов" },
                { "Save log", "Сохранить лог" },
                { "Saves", "Сохранений" },
                { "SB construction", "Строительство НБ" },
                { "Scan", "Сканер" },
                { "Scan Locked", "Скан запрещен" },
                { "Scan Prot.", "Мощность" },
                { "Scaner", "Сканер" },
                { "Scanner", "Сканер" },
                { "Scanner Cache", "Сканерный кэш" },
                { "Scavenger", "Свободный пират" },
                { "Science", "Ученые" },
                { "Science progress", "Научный прогресс" },
                { "Screenshot", "Скриншот" },
                { "Screw-on", "Навинт" },
                { "Script", "Скрипт" },
                { "Script Cache", "Кэш скриптов" },
                { "Script Cache Entry", "Кеш скрипта" },
                { "Script editor", "Редактор скриптов" },
                { "Script Item", "Скриптовый предмет" },
                { "Script Name", "Имя скрипта" },
                { "Script Ord. Abs.", "Скриптовый приказ" },
                { "Script Ship", "Скриптовый корабль" },
                { "Script Tag", "Тег скрипта" },
                { "Scripts", "Скрипты" },
                { "Scripts only", "Только скрипты" },
                { "Scroll — zoom · RMB drag — pan · LMB drag object — move · Click — edit", "Колесико — масштаб · ПКМ зажать — перемещение · ЛКМ зажать объект — двигать · Клик — редактировать" },
                { "Search", "Поиск" },
                { "Search path or value…", "Поиск по пути/значению…" },
                { "Sec. Dmg Radius", "Радиус доп. урона" },
                { "Secondary Graph", "Доп. графика" },
                { "Sector", "Сектор" },
                { "Sectors", "Сектора" },
                { "Seek Items", "Подбор предметов" },
                { "Select folder…", "Выбрать папку…" },
                { "selected", "выбрано" },
                { "Series", "Серия" },
                { "Series Info", "Информация о серии" },
                { "Set", "Сет" },
                { "Settings", "Настройки" },
                { "Shadow Empire", "Тень империи" },
                { "Ship", "Корабль" },
                { "ship ", "корабль " },
                { "Ship / Station", "Корабль / Станция" },
                { "Ship already used in another script", "Корабль уже есть в другом скрипте" },
                { "Ship Bad", "Текущий враг" },
                { "Ship Counts", "Количество кораблей" },
                { "Ship Destroy", "Уничтожение" },
                { "Ship Good", "Текущий друг" },
                { "Ship ID", "ID корабля" },
                { "Ship Infos", "Инфо кораблей" },
                { "Ship minus", "Поломка корабля" },
                { "Ship Name", "Имя корабля" },
                { "Ship plus", "Корабль" },
                { "Ship: ", "Корабль: " },
                { "Ships", "Кораблей" },
                { "Ships Fried by stars", "Кораблей об звезду" },
                { "Shock", "Шоковый" },
                { "Shocker-5300", "Шоккер-5300" },
                { "Shop", "Магазин" },
                { "Shop Goods", "Магазин товаров" },
                { "Shop Items", "Магазин оборудования" },
                { "Shot Count", "Кол. выстрелов" },
                { "Shot spd", "Скор.выстрела" },
                { "Shot Type", "Тип выстрела" },
                { "Shots", "Выстрелы" },
                { "Showing", "Показано" },
                { "Shtip", "Штип" },
                { "Size", "Размер" },
                { "Size Mod.", "Мод.размера" },
                { "Skill: Accuracy", "Навык: Точность" },
                { "Skill: Charm", "Навык: Обаяние" },
                { "Skill: Leadership", "Навык: Лидерство" },
                { "Skill: Mobility", "Навык: Маневренность" },
                { "Skill: Technics", "Навык: Техника" },
                { "Skill: Trade", "Навык: Торговля" },
                { "Skills", "Навыки" },
                { "Skipper", "Шкипер" },
                { "Slot", "Слот" },
                { "Slot is occupied by another item", "Слот занят другим предметом" },
                { "Slot: Art", "Слот: Артефакт" },
                { "Slot: Def", "Слот: ГЗП" },
                { "Slot: Droid", "Слот: Дроид" },
                { "Slot: Forsage", "Слот: Форсаж" },
                { "Slot: Hook", "Слот: Захват" },
                { "Slot: Radar", "Слот: Радар" },
                { "Slot: Scaner", "Слот: Сканер" },
                { "Slot: Weapon", "Слот: Оружие" },
                { "Slots", "Слоты" },
                { "Slowly increases with the player hull size", "Медленно растет с увеличением корпуса игрока" },
                { "Smersh", "Смерш" },
                { "Sort A–Z", "Сортировка А–Я" },
                { "Sort by planet", "Сортировка по планете" },
                { "Sort by price", "Сортировка по цене" },
                { "Sort by weight", "Сортировка по весу" },
                { "Sound Type", "Тип звука" },
                { "Source", "Источник" },
                { "Special", "Особое" },
                { "Special (Acryn)", "Акрин" },
                { "Special Ship", "Специальный корабль" },
                { "Specific", "Конкретный" },
                { "Speed", "Скорость" },
                { "Speed Hill", "Скорость горы" },
                { "Speed Land", "Скорость равнина" },
                { "Speed Max", "Макс.скорость" },
                { "Speed Min", "Мин.скорость" },
                { "Speed Water", "Скорость вода" },
                { "Speed X", "Скорость X" },
                { "Speed Y", "Скорость Y" },
                { "Splash", "Осколочный" },
                { "Splinter", "Осколочный" },
                { "Split missile damage bonuses", "Бонусы к урону ракетного оружия разделяются на ракеты в залпе" },
                { "Sponsor", "Спонсор" },
                { "Sputniks", "Спутники" },
                { "Star", "Система" },
                { "Star 1 End", "Звезда 1" },
                { "Star 2 End", "Звезда 2" },
                { "Star damage multiplier", "Урон от звезд" },
                { "Star ID", "ID системы" },
                { "Star Infos", "Инфо звёзд" },
                { "Star Rangers", "Рейнджеры" },
                { "Star Transport", "Транспорт" },
                { "Star: ", "Система: " },
                { "Stars", "Звезд" },
                { "Start system in galaxy center", "Расположение стартовой системы игрока в центре" },
                { "Start Turn", "Ход начала" },
                { "Starting tech bonus", "Бонус к стартовым технологиям" },
                { "State", "Состояние" },
                { "State Num", "Состояние" },
                { "Station", "Станция" },
                { "Station Satellite", "Спутник станции" },
                { "Station Shop Goods", "Магазин товаров станции" },
                { "Station Shop Items", "Предметы магазина станции" },
                { "Stations", "Станций" },
                { "Stations use equipment from own shop", "Станции могут получать новое оборудование из собственного магазина" },
                { "Statistics", "Статистика" },
                { "Stats", "Статистика" },
                { "Status", "Статус" },
                { "Status Effects", "Эффекты" },
                { "Step Angle", "Угол шага" },
                { "Stim capacity", "Стимуляторы" },
                { "Stimulants Used", "Использовал стим." },
                { "Stimulators", "Стимуляторы" },
                { "Storage", "Склад" },
                { "Storage Place", "Место хранения" },
                { "Storages", "Склады" },
                { "Stored Items", "Хранилище предметов" },
                { "Strength", "Сила" },
                { "String", "Строка" },
                { "Structure", "Структура" },
                { "Structure errors", "Ошибки структуры" },
                { "Submodem", "Сабмодем" },
                { "Subportal", "Субпортал" },
                { "Subtype", "Подтип" },
                { "Successful", "Выполнено" },
                { "supported", "поддерживается" },
                { "Supporter", "Клан.пират (поддержка)" },
                { "Surface", "Поверхность" },
                { "Swallower", "Проглот" },
                { "Sys Name", "Системное имя" },
                { "System map", "Карта системы" },
                { "System shutdown", "Системное отключение" },
                { "Systems taken by pirates", "Захвачено пират.кланом" },
                { "Take Items", "Поднять предметы" },
                { "take off", "взлет" },
                { "Talk Locked", "Интерком закрыт" },
                { "Target", "Цель" },
                { "target lost", "цель потеряна" },
                { "Target Max Defense", "Самая бронированная цель" },
                { "Target Max Distance", "Отдаленная цель" },
                { "Target Max HP", "Цель с макс. HP" },
                { "Target Max Strength", "Самая мощная цель" },
                { "Target Min Distance", "Ближайшая цель" },
                { "Target Min HP", "Цель с мин. HP" },
                { "Target system", "Система" },
                { "Target Type", "Тип цели" },
                { "Targeting Block Droid", "Блокировка дроида" },
                { "Targeting Block Weapon", "Блокировка оружия" },
                { "Targeting Damaged", "Бонус урона (поврежденная цель)" },
                { "Targeting Drop Cargo", "Сброс груза" },
                { "Targeting More Drop", "Увеличенный шанс сброса" },
                { "Targeting Reduce Engine", "Увеличение износа двигателя" },
                { "Targeting Scan", "Бонус урона (мощный сканер)" },
                { "Tech", "Оборудование" },
                { "Tech level", "Тех.уровень" },
                { "Tech Lvl Know", "Знание тех.уровня" },
                { "Tech Radius", "Тех. радиус" },
                { "Technics", "Техника" },
                { "Teleport", "Телепорт" },
                { "teleport to system ", "телепорт в систему " },
                { "Terron", "Террон" },
                { "terronoids", "терроноиды" },
                { "Text", "Текст" },
                { "Text 1", "Текст [1]" },
                { "Text 2", "Текст [2]" },
                { "Text 3", "Текст [3]" },
                { "Text Data", "Текстовые данные" },
                { "Text quest", "Текстовый квест" },
                { "Theme", "Тема" },
                { "Time", "Время" },
                { "Timers & Flags", "Таймеры и флаги" },
                { "Tips & Tutorials", "Обучение" },
                { "TL", "ТУ" },
                { "To system", "В систему" },
                { "Torpedo", "Торпеда" },
                { "Torpedo Tube", "Торпедный аппарат" },
                { "Total Kills", "Всего убийств" },
                { "Trade", "Торговля" },
                { "Trade Penalty", "Штраф торговли" },
                { "Trader", "Торговец" },
                { "Tranclucator", "Транклюкатор" },
                { "Tranclucator Ship", "Корабль транклюкатора" },
                { "Tranclucators", "Транклюкаторы" },
                { "Transfactorial Beacon", "Трансфакторный маяк" },
                { "Transport", "Транспорт" },
                { "Transport subsidy", "Поддержка транспорта" },
                { "Transport Type", "Тип транспорта" },
                { "Transports", "Транспорты" },
                { "Treasure Map", "Карта сокровищ" },
                { "Treton", "Третон" },
                { "Trophies", "Трофеи" },
                { "Turbogravitron", "Турбогравир" },
                { "Turn", "Ход" },
                { "Turn Create", "Ход создания" },
                { "Turn Vars", "Turn переменные" },
                { "Turn: ", "ID: " },
                { "Turrets Built", "Построено турелей" },
                { "Turrets Destroyed", "Уничтожено турелей" },
                { "Type", "Тип" },
                { "Type-specific", "Типовые" },
                { "Types", "Типы" },
                { "Undefendable", "Игнорирующий защиту" },
                { "Unk. Done", "Посетил нез.планет" },
                { "unsupported", "не поддерживается" },
                { "Urgant", "Ургант" },
                { "Use Count", "Кол. запусков" },
                { "used", "используется" },
                { "Useless", "Ошметки" },
                { "Useless Item", "Useless" },
                { "User message", "Пользовательское" },
                { "Value", "Значение" },
                { "Variable", "Переменная" },
                { "Velocity", "Вектор скорости" },
                { "Vertix", "Вертикс" },
                { "View Infections", "Инфекции" },
                { "View Sets", "Сеты" },
                { "Visible", "Открыт" },
                { "Visible (click to hide)", "Открыт (нажмите, чтобы закрыть)" },
                { "Visited", "Посещена" },
                { "W Energy", "Урон энергетический" },
                { "W Missile", "Урон ракетный" },
                { "W Radius", "Радиус оружия" },
                { "W Splinter", "Урон осколочный" },
                { "W-Coder", "W-Кодер" },
                { "War", "Дельта сил сторон" },
                { "War operation", "Военная операция" },
                { "War Operations", "Военные операции" },
                { "War subsidy", "Военная субсидия" },
                { "Warrior", "Военный" },
                { "Warrior Type", "Тип военного" },
                { "Warriors", "Военные" },
                { "Water", "Вода" },
                { "Wave Phaser", "Волновой фазер" },
                { "WB construction", "Строительство ВБ" },
                { "WB Give Day", "Ход получения на ВБ" },
                { "WB Programmes", "Программы с ВБ" },
                { "Weapon", "Оружие" },
                { "Weapon block", "Блок оружия" },
                { "Weapon ID", "ID оружия" },
                { "Weapon Shortage", "Дефицит оружия" },
                { "Weapon Type", "Тип оружия" },
                { "Weapons", "Оружие" },
                { "Wear", "Надежность" },
                { "Weight", "Вес" },
                { "Width", "Ширина" },
                { "Wingman", "Капитан" },
                { "X", "X" },
                { "Y", "Y" },
                { "Year", "Год" },
                { "Yes", "Да" },
                { "Z", "Z" },
                { "Zing", "Вжик" },
                { "Zonds", "Зонды" },
            };
        private static readonly Dictionary<string, string> EnglishByRussian = BuildReverse();

        internal static bool TryRussian(string english, out string russian)
        {
            return RussianByEnglish.TryGetValue(english ?? string.Empty, out russian);
        }

        internal static bool TryEnglish(string russian, out string english)
        {
            return EnglishByRussian.TryGetValue(russian ?? string.Empty, out english);
        }

        private static Dictionary<string, string> BuildReverse()
        {
            Dictionary<string, string> result =
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (KeyValuePair<string, string> pair in RussianByEnglish)
                if (!result.ContainsKey(pair.Value)) result.Add(pair.Value, pair.Key);
            return result;
        }
    }
}
